### ISSUE TITLE
Layout 진행상황

### ISSUE THREAD

**Issue by memeze** [ckdgml6556/RxProject#15]
## 개요
> UI 팀의 레이아웃 구성 진행상황 공유 issue 입니다.

## TODO List
- [x] xml 임시 등록
- [x] Constraint Layout 숙지
- [x] Material Design 숙지

### Activity
- [x] activity_splash
- [x] activity_sign_in
- [ ] activity_trip_album
- [ ] activity_main
- [x] activity_more_user
- [ ] activity_more_notice
- [ ] activity_more_theme
- [ ] activity_trip_info
- [x] activity_trip_account
- [ ] activity_trip_check
- [x] activity_trip_member
- [ ] activity_trip_plan

### Fragment
- [ ] fragment_main_home
- [x] fragment_main_trip
- [ ] fragment_main_search
- [x] fragment_main_more

### Adapter item
- [ ] item_main_home_trip_log
- [ ] item_main_trip_plan
- [ ] item_main_trip_log
- [ ] item_main_search
- [ ] item_trip_plan
- [ ] item_trip_check
- [x] item_trip_account
- [x] item_trip_member
- [ ] item_trip_album

**Comment by bellKong** [comment]
개발자 Bellkong 

Activity
- activitiy_trip_member
- activitiy_trip_account

Adapter item
-  item_trip_account
-  item_trip_member

**Comment by wallywalk** [comment]
병아리 개발자 hyuna

Activity
- activity_splash
- activity_sign_in
- activity_more_user
- activity_main

Fragment
- fragment_main_trip
- fragment_main_more
