### ISSUE TITLE
[ Seminar ] Rx세미나 일정

### ISSUE THREAD

**Issue by ckdgml6556** [ckdgml6556/RxProject#3]
## Rx세미나 일정
> RxJava 프로젝트 진행을 위한 세미나 진행 스케줄
- 교재 : 리액티브 안드로이드 프로그래밍 [RxJava로 안드로이드 애플리케이션 제작하기]

## 1주차
> 2020.01.13
- [x] Git세미나 [ `김민재` ] #1 
- [x] Retrofit세미나 [ `박창희` ] #2 

## 2주차 
> 2020.01.20
- [x] 1장 첫"Hello World" RxJava 애플리케이션 만들기 [ `김보민` ]
- [x] 2장 기본 RxJava의 이해 [ `박창희` ] #8 

## 3주차
> 2020.02.03
- [x] Nosql 세미나 [ `이상민` ] #6 

## 4주차
- [x] Realm세미나 - 기본편 [ `김현아` ]
- [x] Realm-Rx사용 [ `임종빈` ] #7 

## 5주차
> 2020.02.17
- [x] Realm 세미나 - 심화편 [ `박창희` ] #10 
- [x] 커스텀 옵저버블 작성 [ `김민재`] #9 

## 6주차
> 2020.02.24 
- [x] 고급 옵저버블 흐름 [ `김민재` ] #12 

## 7주차
> 2020.03.02
- [ ] 7장 RxJAVA와 액티비티 생명 주기 [ `박창희` ]
- [x] 10장 고차원 추상화 [ `임종빈` ]

## 8주차
> 2020.03.13
- [x] 3장 주식 데이터를 가져오면서 레트로핏 사용법 배우기 [ `김현아` ]
- [ ] 11장 서브젝트의 기본과 환경 설정 저장 [ `이상민` ]
- [ ] ACC를 이용한 MVP패턴과 MVVM패턴 [ `김보민`, `김현아` ]
